name: Deploy Functions
on:
  push:
    branches:
    - master
    paths:
      - 'functions/*'
jobs:
  main:
    name: Build and Deploy Functions
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Firebase
      uses: doonstore/firebase-deploy@v1
      with:
        params: --only functioins
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT }}
